services:
  app:
    image: ghcr.io/jvaltteri/qure:latest
    container_name: qure
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/app/server/config.json:ro
      - ./db/:/app/server/db/

      - ./logo.png:/app/client/dist/logo.png:ro
      - ./images/:/app/client/dist/images/:ro

    # --- Security Hardening --- #
    cap_drop: [ALL]     # Drop all kernel capabilities for security
    cap_add: []         # Do not add anything back

    read_only: true     # 6. Read-Only Root Filesystem
    # ---                    --- #

    restart: unless-stopped
