name: Frontend Coverage
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    strategy:
      matrix:
        node:
          - 22
    name: Generate test coverage badge
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: 'Cache node_modules'
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-v${{ matrix.node }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-v${{ matrix.node }}-

    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: npm install

    - name: Generate coverage results
      run: npm run cover

    - name: Generate a coverage value
      id: coverage
      # Generates a GitHub Workflow output named `lines`
      run: |
        COVERAGE="$( grep -C 1 "Branches" ./coverage/lcov-report/index.html | grep % |  sed 's/^[^0-9]*//' | sed 's/^[ \t]*\([0-9]\+\)[^0-9].*$/\1/' ) )"
        echo "##[set-output name=lines;]${COVERAGE}%"

    - name: Generate the badge SVG image
      uses: emibcn/badge-action@v2.0.3
      id: badge
      with:
        label: 'Frontend test coverage'
        status: ${{ steps.coverage.outputs.lines }}
        color: 'blue'
        path: ${{ steps.coverage.outputs.path }}

    - name: Upload badge as artifact
      uses: actions/upload-artifact@v4
      with:
        name: badge
        path: ${{ steps.coverage.outputs.path }}
        if-no-files-found: error

    - name: Commit badge
      continue-on-error: true
      env:
        BADGE: ${{ steps.coverage.outputs.path }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add "${BADGE}"
        git commit -m "Add/Update badge"

    - name: Push badge commit
      uses: ad-m/github-push-action@master
      if: ${{ success() }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.coverage.outputs.branch }}
