name: Backend Coverage
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    strategy:
      matrix:
        node:
          - 22
    name: Generate test coverage badge
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: 'Cache node_modules'
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-v${{ matrix.node }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-v${{ matrix.node }}-

    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: npm install

    - name: Generate coverage results
      run: npm run cover

    - name: Generate a coverage value
      id: coverage
      # Generates a GitHub Workflow output named `lines`
      run: |
        COVERAGE="$( grep -C 1 "Branches" ./coverage/lcov-report/index.html | grep % |  sed 's/^[^0-9]*//' | cut -c -4 )"
        echo "##[set-output name=lines;]${COVERAGE}%"

    # Use the output from the `coverage` step
    - name: Generate the badge SVG image
      uses: emibcn/badge-action@v1
      with:
        label: 'Frontend test coverage'
        status: ${{ steps.coverage.outputs.lines }}
        color: 'blue,green'
        path: badge.svg
